### PR TITLE
Add duration, delay, and fontSizeFactor properties to ReactBubbleChart component

### PR DESCRIPTION
**Pull request by jwdomingo**
We can add further customization to the bubble transition animations as well as the appearance of the text labels by passing in a few new properties. The proposed options are as follows:
#### **`duration`**
- Represents the length of time (in milliseconds) it takes for each bubble's transition animation to complete. The transition duration defaults to 500 ms (as per the original spec) but can be set to zero (helps reduce jitteriness when there are many bubbles and animations are not necessary).

```
circles.transition()
  .duration(duration)
```

_Example:_`<ReactBubbleChart duration={0} />`

---
#### **`delay`**
- Represents the length of time (in milliseconds) used to delay (stagger) the start of each bubble element's transition animation. Defaults to 7 ms (as per original spec) but can also be set to zero. Zeroing out the transition staggers can reduce jitteriness.

```
circles.transition()
  .duration(duration)
  .delay((d, i) => i * delay)
```

_Example:_ `<ReactBubbleChart duration={0} delay={0} />`

---
#### **`fontSizeFactor`**
- Can pass a multiplier used to calculate the font-size of each text label. If provided, each bubble's font size will be a function of its radius (i.e., a radius is multiplied by the fontSizeFactor to determine a pixel-unit font-size).
- If not specified, the font-sizes will depend on the normal CSS styles for the `large`, `medium`, and `small` classes, or 1em by default (if size classes are not defined). Setting font-size to null voids the style method.

```
const fontFactor = this.fontSizeFactor
labels.style('font-size', d => fontFactor ? fontFactor *  d.r + 'px' : null)
```

_Example:_ `<ReactBubbleChart fontSizeFactor={0.5} />`

screen shot 2016-03-23 at 10 01 25 am

### CODE REVIEW

**Comment by kauffecup** [comment]
this looks awesome!

two tiny requests:
  • could you wrap the text in the readme to 80chars per line?
  • can you add that photo to the repo and inline it in the readme?

**Comment by jwdomingo** [comment]
Can do!

**Comment by jwdomingo** [comment]
Do you want me to create a dir containing the photo and link a rel path to it? I noticed your gif is hosted on imgur.

**Comment by kauffecup** [comment]
it's fine if you want to put it in this repo! up to you

**Comment by kauffecup** [comment]
thanks again! this is awesome! i'll update the node version when i get a chance later

**Comment by jwdomingo** [comment]
That would be awesome, I'm using it in a project right now :+1:

**Comment by kauffecup** [comment]
sorry this took me so long! these changes are now live in v0.4.0 on npm

**Pull request merged**
